# Generated by Django 4.0.3 on 2022-04-02 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0007_alter_post_slug_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('coding', 'coding'), ('coding', 'sports'), ('coding', 'life')], max_length=255),
        ),
    ]
